// Atividades profissionais conforme formulário ART do CONFEA
export const ATIVIDADES_PROFISSIONAIS: string[] = [
  'Supervisão, Coordenação e Orientação Técnica',
  'Coleta de Dados',
  'Estudo',
  'Planejamento',
  'Projeto',
  'Especificação',
  'Orçamento',
  'Execução de Obra ou Serviço',
  'Construção',
  'Reforma',
  'Ampliação',
  'Manutenção',
  'Reparo',
  'Vistoria',
  'Perícia',
  'Avaliação',
  'Arbitramento',
  'Fiscalização',
  'Elaboração de Laudo e/ou Parecer Técnico',
  'Assistência, Assessoria e Consultoria',
  'Elaboração de Orçamento',
  'Gerenciamento e Administração',
  'Pesquisa Tecnológica',
  'Produção Técnica',
  'Ensino de Técnica Profissional',
]

export const UNIDADES: string[] = [
  'm2',
  'm3',
  'm',
  'km',
  'ha',
  'un',
  'vb',
  'kg',
  't',
  'h',
  'mes',
  'conj',
]

export const DEFAULT_STAGES: string[] = [
  'Servicos preliminares',
  'Fundacao',
  'Estrutura',
  'Alvenaria',
  'Cobertura',
  'Instalacoes hidrosanitarias',
  'Instalacoes eletricas',
  'Revestimento',
  'Pintura',
  'Acabamento e limpeza',
]
